//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConsumeServicio.WservicioBDD {
    using System.Data;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="WservicioBDD.WebServiceBDDSoap")]
    public interface WebServiceBDDSoap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/WSselect_Usuario", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet WSselect_Usuario();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/WSselect_Usuario", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataSet> WSselect_UsuarioAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/WSValidar_Usuario", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        bool WSValidar_Usuario(int id, int contrasena);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/WSValidar_Usuario", ReplyAction="*")]
        System.Threading.Tasks.Task<bool> WSValidar_UsuarioAsync(int id, int contrasena);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/WSBuscar_Usuario_ID", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet WSBuscar_Usuario_ID(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/WSBuscar_Usuario_ID", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataSet> WSBuscar_Usuario_IDAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/WSBuscar_Usuario_ID_Nombre", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet WSBuscar_Usuario_ID_Nombre(string nombre);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/WSBuscar_Usuario_ID_Nombre", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataSet> WSBuscar_Usuario_ID_NombreAsync(string nombre);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/WSinsert_Usuario", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string WSinsert_Usuario(int id_clinica, string nombre_usuario, string apellido_usuario, string fecha_nac, string dpi, int nit, string direccion, string correo, int no_telelefono, int contrasena);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/WSinsert_Usuario", ReplyAction="*")]
        System.Threading.Tasks.Task<string> WSinsert_UsuarioAsync(int id_clinica, string nombre_usuario, string apellido_usuario, string fecha_nac, string dpi, int nit, string direccion, string correo, int no_telelefono, int contrasena);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Actualizar_Usuario", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        void Actualizar_Usuario(int id_usuario, int id_clinica, string nombre_usuario, string apellido_usuario, string fecha_nac, string dpi, int nit, string direccion, string correo, int no_telelefono, int contrasena);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Actualizar_Usuario", ReplyAction="*")]
        System.Threading.Tasks.Task Actualizar_UsuarioAsync(int id_usuario, int id_clinica, string nombre_usuario, string apellido_usuario, string fecha_nac, string dpi, int nit, string direccion, string correo, int no_telelefono, int contrasena);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/WSselect_Clinica", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet WSselect_Clinica();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/WSselect_Clinica", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataSet> WSselect_ClinicaAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/WSinsert_Clinica", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string WSinsert_Clinica(int id_clinica, string nombre_clinica, string direccion, string correo, int no_telelefono, int nit);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/WSinsert_Clinica", ReplyAction="*")]
        System.Threading.Tasks.Task<string> WSinsert_ClinicaAsync(int id_clinica, string nombre_clinica, string direccion, string correo, int no_telelefono, int nit);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/WSBorrar_Clinica", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        void WSBorrar_Clinica(int id_clinica);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/WSBorrar_Clinica", ReplyAction="*")]
        System.Threading.Tasks.Task WSBorrar_ClinicaAsync(int id_clinica);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/WSActualizar_Clinica", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        void WSActualizar_Clinica(int id_clinica, string nombre_clinica, string direccion, string correo, int no_telelefono, int nit);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/WSActualizar_Clinica", ReplyAction="*")]
        System.Threading.Tasks.Task WSActualizar_ClinicaAsync(int id_clinica, string nombre_clinica, string direccion, string correo, int no_telelefono, int nit);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface WebServiceBDDSoapChannel : ConsumeServicio.WservicioBDD.WebServiceBDDSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WebServiceBDDSoapClient : System.ServiceModel.ClientBase<ConsumeServicio.WservicioBDD.WebServiceBDDSoap>, ConsumeServicio.WservicioBDD.WebServiceBDDSoap {
        
        public WebServiceBDDSoapClient() {
        }
        
        public WebServiceBDDSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WebServiceBDDSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebServiceBDDSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebServiceBDDSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.Data.DataSet WSselect_Usuario() {
            return base.Channel.WSselect_Usuario();
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> WSselect_UsuarioAsync() {
            return base.Channel.WSselect_UsuarioAsync();
        }
        
        public bool WSValidar_Usuario(int id, int contrasena) {
            return base.Channel.WSValidar_Usuario(id, contrasena);
        }
        
        public System.Threading.Tasks.Task<bool> WSValidar_UsuarioAsync(int id, int contrasena) {
            return base.Channel.WSValidar_UsuarioAsync(id, contrasena);
        }
        
        public System.Data.DataSet WSBuscar_Usuario_ID(int id) {
            return base.Channel.WSBuscar_Usuario_ID(id);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> WSBuscar_Usuario_IDAsync(int id) {
            return base.Channel.WSBuscar_Usuario_IDAsync(id);
        }
        
        public System.Data.DataSet WSBuscar_Usuario_ID_Nombre(string nombre) {
            return base.Channel.WSBuscar_Usuario_ID_Nombre(nombre);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> WSBuscar_Usuario_ID_NombreAsync(string nombre) {
            return base.Channel.WSBuscar_Usuario_ID_NombreAsync(nombre);
        }
        
        public string WSinsert_Usuario(int id_clinica, string nombre_usuario, string apellido_usuario, string fecha_nac, string dpi, int nit, string direccion, string correo, int no_telelefono, int contrasena) {
            return base.Channel.WSinsert_Usuario(id_clinica, nombre_usuario, apellido_usuario, fecha_nac, dpi, nit, direccion, correo, no_telelefono, contrasena);
        }
        
        public System.Threading.Tasks.Task<string> WSinsert_UsuarioAsync(int id_clinica, string nombre_usuario, string apellido_usuario, string fecha_nac, string dpi, int nit, string direccion, string correo, int no_telelefono, int contrasena) {
            return base.Channel.WSinsert_UsuarioAsync(id_clinica, nombre_usuario, apellido_usuario, fecha_nac, dpi, nit, direccion, correo, no_telelefono, contrasena);
        }
        
        public void Actualizar_Usuario(int id_usuario, int id_clinica, string nombre_usuario, string apellido_usuario, string fecha_nac, string dpi, int nit, string direccion, string correo, int no_telelefono, int contrasena) {
            base.Channel.Actualizar_Usuario(id_usuario, id_clinica, nombre_usuario, apellido_usuario, fecha_nac, dpi, nit, direccion, correo, no_telelefono, contrasena);
        }
        
        public System.Threading.Tasks.Task Actualizar_UsuarioAsync(int id_usuario, int id_clinica, string nombre_usuario, string apellido_usuario, string fecha_nac, string dpi, int nit, string direccion, string correo, int no_telelefono, int contrasena) {
            return base.Channel.Actualizar_UsuarioAsync(id_usuario, id_clinica, nombre_usuario, apellido_usuario, fecha_nac, dpi, nit, direccion, correo, no_telelefono, contrasena);
        }
        
        public System.Data.DataSet WSselect_Clinica() {
            return base.Channel.WSselect_Clinica();
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> WSselect_ClinicaAsync() {
            return base.Channel.WSselect_ClinicaAsync();
        }
        
        public string WSinsert_Clinica(int id_clinica, string nombre_clinica, string direccion, string correo, int no_telelefono, int nit) {
            return base.Channel.WSinsert_Clinica(id_clinica, nombre_clinica, direccion, correo, no_telelefono, nit);
        }
        
        public System.Threading.Tasks.Task<string> WSinsert_ClinicaAsync(int id_clinica, string nombre_clinica, string direccion, string correo, int no_telelefono, int nit) {
            return base.Channel.WSinsert_ClinicaAsync(id_clinica, nombre_clinica, direccion, correo, no_telelefono, nit);
        }
        
        public void WSBorrar_Clinica(int id_clinica) {
            base.Channel.WSBorrar_Clinica(id_clinica);
        }
        
        public System.Threading.Tasks.Task WSBorrar_ClinicaAsync(int id_clinica) {
            return base.Channel.WSBorrar_ClinicaAsync(id_clinica);
        }
        
        public void WSActualizar_Clinica(int id_clinica, string nombre_clinica, string direccion, string correo, int no_telelefono, int nit) {
            base.Channel.WSActualizar_Clinica(id_clinica, nombre_clinica, direccion, correo, no_telelefono, nit);
        }
        
        public System.Threading.Tasks.Task WSActualizar_ClinicaAsync(int id_clinica, string nombre_clinica, string direccion, string correo, int no_telelefono, int nit) {
            return base.Channel.WSActualizar_ClinicaAsync(id_clinica, nombre_clinica, direccion, correo, no_telelefono, nit);
        }
    }
}
